run:
  concurrency: 4
  go: "1.23"
  tests: true

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 3
    min-occurrences: 3
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 120
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  unparam:
    check-exported: false

issues:
  max-same-issues: 3
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - gocyclo
        - gosec
    - path: internal/hmac/
      text: weak cryptographic primitive
      linters:
        - gosec
    - text: 'SA9003:'
      linters:
        - staticcheck
    - source: '^//go:generate '
      linters:
        - lll
  exclude-dirs:
    - third_party
    - builtin
    - examples
    - tools
